# Generated by Django 4.2.25 on 2025-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
        migrations.AddField(
            model_name='userdata',
            name='contact_no',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.CharField(default='default_location', max_length=100),
            preserve_default=False,
        ),
    ]
