# Generated by Django 4.2.25 on 2025-11-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userdata_age_remove_userdata_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
