# Generated by Django 5.2.7 on 2025-11-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userdata_language_alter_userdata_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('law_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('section_no', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sourcelink', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
