# Generated by Django 5.2.7 on 2025-11-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_legaltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaltemplate',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='legal_templates/'),
        ),
    ]
