# Generated by Django 5.2.7 on 2025-11-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_legaltemplate_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('advocate_id', models.AutoField(primary_key=True, serialize=False)),
                ('advocate_name', models.CharField(max_length=255)),
                ('specilaization', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('experiance_years', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('availability_status', models.BooleanField(default=True)),
            ],
        ),
    ]
