# Generated by Django 5.2.7 on 2025-11-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_advocate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='advocate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advocates/'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='password',
            field=models.CharField(blank=True, default='temp123', max_length=255, null=True),
        ),
    ]
