# Generated by Django 5.2.7 on 2025-11-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_advocate_contact_info_advocate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
