# Generated by Django 5.2.7 on 2025-11-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_advocate_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advocate',
            name='password',
            field=models.CharField(default='temp1234', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advocate',
            name='qualification',
            field=models.CharField(blank=True, default='Not Provided', max_length=500),
            preserve_default=False,
        ),
    ]
