# Generated by Django 5.2.7 on 2025-11-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_advocate_email_alter_advocate_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='experiance_years',
            new_name='experience_years',
        ),
        migrations.RenameField(
            model_name='advocate',
            old_name='specilaization',
            new_name='specialization',
        ),
    ]
