# Generated by Django 5.2.7 on 2025-11-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_experiance_years_advocate_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advocate',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
