# Generated by Django 5.2.7 on 2025-11-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_advocate_is_verified_advocate_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('challan_no', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
    ]
