# Generated by Django 5.2.7 on 2025-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awareness_content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
