# Generated by Django 5.2.7 on 2025-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='bar_council_idcard',
            field=models.FileField(blank=True, null=True, upload_to='advocate_idcards/'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='enrollment_number',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
       migrations.AlterField(
    model_name='advocate',
    name='state_bar_council',
    field=models.CharField(max_length=255, null=True, blank=True),
)

    ]
