# Generated by Django 5.2.7 on 2025-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_advocate_bar_council_idcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='enrollment_number',
            field=models.CharField(max_length=100),
        ),
    ]
