# Generated by Django 5.2.7 on 2025-12-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_advocate_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
