# Generated by Django 5.2.7 on 2025-12-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_advocate_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='state_bar_council',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
