# Generated by Django 5.2.7 on 2025-12-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_advocate_state_bar_council'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='state_bar_council',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
