# Generated by Django 5.2.7 on 2025-12-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_advocate_state_bar_council'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='punishment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
