# Generated by Django 5.2.7 on 2025-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_law_punishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='bailable_status',
            field=models.CharField(blank=True, help_text='e.g. Bailable or Non-Bailable', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='cognizable_status',
            field=models.CharField(blank=True, help_text='e.g. Cognizable or Non-Cognizable', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='triable_by',
            field=models.CharField(blank=True, help_text='e.g. Magistrate of First Class', max_length=200, null=True),
        ),
    ]
