# Generated by Django 5.2.7 on 2025-12-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_law_bailable_status_law_cognizable_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='legal_office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('offences_handled', models.TextField()),
                ('working_hours', models.CharField(max_length=100)),
            ],
        ),
    ]
