# Generated by Django 5.2.7 on 2025-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_legal_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('challan_no', models.AutoField(primary_key=True, serialize=False)),
                ('offence_type', models.CharField(max_length=255)),
                ('offence_location', models.CharField(max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
