# Generated by Django 5.2.7 on 2025-12-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_challan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='offence_type',
            field=models.CharField(choices=[('Driving without License', 'Driving without License'), ('Driving without Helmet', 'Driving without Helmet'), ('Driving without Seatbelt', 'Driving without Seatbelt'), ('Overspeeding', 'Overspeeding'), ('Jumping Red Light', 'Jumping Red Light'), ('Wrong Side Driving', 'Wrong Side Driving'), ('Illegal Parking', 'Illegal Parking'), ('Driving without Insurance', 'Driving without Insurance'), ('Driving without PUC Certificate', 'Driving without PUC Certificate'), ('Driving under Influence', 'Driving under Influence'), ('Using Mobile While Driving', 'Using Mobile While Driving'), ('Vehicle Overloading', 'Vehicle Overloading'), ('Failure to Produce Documents', 'Failure to Produce Documents'), ('Rash and Negligent Driving', 'Rash and Negligent Driving')], max_length=255),
        ),
    ]
