# Generated by Django 5.2.7 on 2025-12-10 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_challan_offence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
        migrations.AlterField(
            model_name='challan',
            name='offence_type',
            field=models.CharField(max_length=255),
        ),
    ]
