# Generated by Django 5.2.7 on 2025-12-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_challan_user_alter_challan_offence_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advocate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
    ]
