"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-(8f^9j8z$3wk8e%@9d8810apue^x@--jsa+simmq74)t)h2m%e'

DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'app', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'project.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'django_db1',
        'USER': 'root',
        'PASSWORD': '',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'app', 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ----------------------------------------------------
# ✉️ EMAIL CONFIGURATION (GMAIL SMTP) – COPY THIS
# ----------------------------------------------------

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_BACKEND = "app.email_backend.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# YOUR GMAIL ADDRESS (replace this)
EMAIL_HOST_USER = "infolawly2025@gmail.com"

# GMAIL APP PASSWORD (NOT your Gmail login password)
EMAIL_HOST_PASSWORD = "gmjo scex wzzt alkf"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# -----------------------------------------------
# 📌 RapidAPI – Instagram Reels Downloader
# -----------------------------------------------
RAPIDAPI_KEY = "fcffe94a9cmsn20b22391e824a94p152c39jsn4ad749cda721"
RAPIDAPI_HOST = "instagram-reels-downloader-api.p.rapidapi.com"
INSTAGRAM_API_URL = "https://instagram-reels-downloader-api.p.rapidapi.com/download"




RAZORPAY_KEY_ID = "rzp_test_SGqoVLiE0K9nhl"
RAZORPAY_KEY_SECRET = "zp7NpWRMCUvMCs4WHC1QmhSn"


# Gemini API Keys (Supports multiple for rotation)
GEMINI_API_KEY = os.environ.get("GOOGLE_API_KEY", "AIzaSyD73LYX8gCLyqaPFbA_Dz0rKulilecO5v0")
_ADDITIONAL_KEYS = [os.environ.get(f"GOOGLE_API_KEY_{i}") for i in range(2, 6)]
GEMINI_API_KEYS = [GEMINI_API_KEY] + [k for k in _ADDITIONAL_KEYS if k]


from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# Force reload for template tags
